### ISSUE TITLE
Editing multiple taxa in workbench

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-frontend#357] opened 2019-09-25 21:33 UTC
When checking multiple boxes in the workbench for editing more than 1 name, the pop-up interface should contain all checked names with a scrollbar so that multiple names can be edited at once. Please see [the thread between @yroskov and @mdoering for more info](https://github.com/Sp2000/colplus-repo/issues/70#issuecomment-534597870) for more details.

![](https://user-images.githubusercontent.com/327505/65523090-08a21980-deec-11e9-8eb5-85a73749a272.png)

**Comment by gdower** [comment] 2019-09-25 21:59
It would also be useful to automatically populate the fields with the data:

![image](https://user-images.githubusercontent.com/8573609/65642077-03a89d00-dfb4-11e9-8b06-46ac914fbd19.png)

![image](https://user-images.githubusercontent.com/8573609/65642794-b3323f00-dfb5-11e9-8e6c-2195cc13ea45.png)


Otherwise if you don't fill in all of the fields manually the API request might overwrite the other unpopulated fields:

```JSON
{
  "name": {
    "scientificName": "Erioptera rhadinostyla",
    "authorship": "Alexander, 1957"
  },
  "lifezones": [],
  "fossil": false,
  "recent": false,
  "mode": "update",
  "datasetKey": "1005",
  "subject": {
    "id": "103734",
    "name": "Erioptera (Unplaced) rhadinostyla Alexander, 1957",
    "rank": "species"
  }
}
```

Actually, the taxonomic editor does allow the user to apply the same decision to multiple names, but probably it wouldn't be the desired action by the user to change all 3 names to be the same name. A user might want to set all 3 names to fossil=True status though:

![image](https://user-images.githubusercontent.com/8573609/65642456-e0cab880-dfb4-11e9-9a0f-b7cfd72d9802.png)

**Comment by mdoering** [comment] 2019-09-25 23:26
mostly a duplicate of #313

**Closed by mdoering** 2019-09-25 23:26 UTC
Labels: design, enhancement
