### ISSUE TITLE
Option Find Taxon in the tree failed to find some taxa, which are present in the tree.

### ISSUE THREAD

**Issue by yroskov** [Sp2000/colplus-frontend#322] opened 2019-08-29 17:33 UTC
Option _Find Taxon_ in the tree failed to find some taxa, which are present in the tree. For example, search for Geranium did not find it. However, Geranium is present in the Tree, if I expand all branches manually, or click button Show Sector in Assembly in right window.
![image](https://user-images.githubusercontent.com/28574252/63962745-0e295280-ca59-11e9-91e8-9173ce129bf5.png)
and
![image](https://user-images.githubusercontent.com/28574252/63962772-200af580-ca59-11e9-99bc-5c100089cc41.png)

**Comment by mdoering** [comment] 2019-08-29 19:58
this has been reported several times already and is a duplicate of https://github.com/Sp2000/colplus-backend/issues/437

It is one of the next issues to work on in the [current prioritization](https://github.com/Sp2000/colplus-backend/projects/3)

**Closed by mdoering** 2019-08-29 19:58 UTC
