### ISSUE TITLE
missing menu items for released catalogues

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-frontend#434] opened 2019-11-27 13:02 UTC
here is one: https://data.catalogue.life/dataset/2053

It seems there is no data. 
Is it because there is no import metric? we could create one as its a release.
But it might be good to check the dataset type and decide which menu items to show based on that.

CATALOGUES so far at least never have import metrics.

**Comment by mdoering** [comment] 2019-11-27 13:04
see also #136 #431 #362

**Comment by thomasstjerne** [comment] 2019-11-27 13:59
Duplicate of #407

**Closed** 2019-11-27 14:33 UTC

**Comment by thomasstjerne** [comment] 2019-11-27 14:39
It was because their datasetKey was < 1001 - I think thats how we used to distinguish the "special ones" from all the GSDs
